name: Deploy Stankopedia

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest Stankopedia
        run: |
          cd /mnt/user/appdata/bigdumbidiot-stankopedia
          git pull origin main
